/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedScriptsRouteImport } from './routes/_authenticated/scripts'
import { Route as AuthenticatedPerformanceRouteImport } from './routes/_authenticated/performance'
import { Route as AuthenticatedInspirationRouteImport } from './routes/_authenticated/inspiration'
import { Route as AuthenticatedIdeasRouteImport } from './routes/_authenticated/ideas'
import { Route as AuthenticatedHooksRouteImport } from './routes/_authenticated/hooks'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedControlRouteImport } from './routes/_authenticated/control'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as ApiPublicRenderCallbackRouteImport } from './routes/api/public/render-callback'
import { Route as ApiPublicAutopilotTickRouteImport } from './routes/api/public/autopilot-tick'
import { Route as AuthenticatedScriptsIdRouteImport } from './routes/_authenticated/scripts.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScriptsRoute = AuthenticatedScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerformanceRoute =
  AuthenticatedPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInspirationRoute =
  AuthenticatedInspirationRouteImport.update({
    id: '/inspiration',
    path: '/inspiration',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIdeasRoute = AuthenticatedIdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHooksRoute = AuthenticatedHooksRouteImport.update({
  id: '/hooks',
  path: '/hooks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedControlRoute = AuthenticatedControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicRenderCallbackRoute = ApiPublicRenderCallbackRouteImport.update({
  id: '/api/public/render-callback',
  path: '/api/public/render-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAutopilotTickRoute = ApiPublicAutopilotTickRouteImport.update({
  id: '/api/public/autopilot-tick',
  path: '/api/public/autopilot-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedScriptsIdRoute = AuthenticatedScriptsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedScriptsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/control': typeof AuthenticatedControlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hooks': typeof AuthenticatedHooksRoute
  '/ideas': typeof AuthenticatedIdeasRoute
  '/inspiration': typeof AuthenticatedInspirationRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/scripts': typeof AuthenticatedScriptsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/scripts/$id': typeof AuthenticatedScriptsIdRoute
  '/api/public/autopilot-tick': typeof ApiPublicAutopilotTickRoute
  '/api/public/render-callback': typeof ApiPublicRenderCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/control': typeof AuthenticatedControlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hooks': typeof AuthenticatedHooksRoute
  '/ideas': typeof AuthenticatedIdeasRoute
  '/inspiration': typeof AuthenticatedInspirationRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/scripts': typeof AuthenticatedScriptsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/scripts/$id': typeof AuthenticatedScriptsIdRoute
  '/api/public/autopilot-tick': typeof ApiPublicAutopilotTickRoute
  '/api/public/render-callback': typeof ApiPublicRenderCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/control': typeof AuthenticatedControlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/hooks': typeof AuthenticatedHooksRoute
  '/_authenticated/ideas': typeof AuthenticatedIdeasRoute
  '/_authenticated/inspiration': typeof AuthenticatedInspirationRoute
  '/_authenticated/performance': typeof AuthenticatedPerformanceRoute
  '/_authenticated/scripts': typeof AuthenticatedScriptsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/scripts/$id': typeof AuthenticatedScriptsIdRoute
  '/api/public/autopilot-tick': typeof ApiPublicAutopilotTickRoute
  '/api/public/render-callback': typeof ApiPublicRenderCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/control'
    | '/dashboard'
    | '/hooks'
    | '/ideas'
    | '/inspiration'
    | '/performance'
    | '/scripts'
    | '/settings'
    | '/scripts/$id'
    | '/api/public/autopilot-tick'
    | '/api/public/render-callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendar'
    | '/control'
    | '/dashboard'
    | '/hooks'
    | '/ideas'
    | '/inspiration'
    | '/performance'
    | '/scripts'
    | '/settings'
    | '/scripts/$id'
    | '/api/public/autopilot-tick'
    | '/api/public/render-callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/calendar'
    | '/_authenticated/control'
    | '/_authenticated/dashboard'
    | '/_authenticated/hooks'
    | '/_authenticated/ideas'
    | '/_authenticated/inspiration'
    | '/_authenticated/performance'
    | '/_authenticated/scripts'
    | '/_authenticated/settings'
    | '/_authenticated/scripts/$id'
    | '/api/public/autopilot-tick'
    | '/api/public/render-callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicAutopilotTickRoute: typeof ApiPublicAutopilotTickRoute
  ApiPublicRenderCallbackRoute: typeof ApiPublicRenderCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scripts': {
      id: '/_authenticated/scripts'
      path: '/scripts'
      fullPath: '/scripts'
      preLoaderRoute: typeof AuthenticatedScriptsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/performance': {
      id: '/_authenticated/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthenticatedPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspiration': {
      id: '/_authenticated/inspiration'
      path: '/inspiration'
      fullPath: '/inspiration'
      preLoaderRoute: typeof AuthenticatedInspirationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ideas': {
      id: '/_authenticated/ideas'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof AuthenticatedIdeasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hooks': {
      id: '/_authenticated/hooks'
      path: '/hooks'
      fullPath: '/hooks'
      preLoaderRoute: typeof AuthenticatedHooksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/control': {
      id: '/_authenticated/control'
      path: '/control'
      fullPath: '/control'
      preLoaderRoute: typeof AuthenticatedControlRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/render-callback': {
      id: '/api/public/render-callback'
      path: '/api/public/render-callback'
      fullPath: '/api/public/render-callback'
      preLoaderRoute: typeof ApiPublicRenderCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/autopilot-tick': {
      id: '/api/public/autopilot-tick'
      path: '/api/public/autopilot-tick'
      fullPath: '/api/public/autopilot-tick'
      preLoaderRoute: typeof ApiPublicAutopilotTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/scripts/$id': {
      id: '/_authenticated/scripts/$id'
      path: '/$id'
      fullPath: '/scripts/$id'
      preLoaderRoute: typeof AuthenticatedScriptsIdRouteImport
      parentRoute: typeof AuthenticatedScriptsRoute
    }
  }
}

interface AuthenticatedScriptsRouteChildren {
  AuthenticatedScriptsIdRoute: typeof AuthenticatedScriptsIdRoute
}

const AuthenticatedScriptsRouteChildren: AuthenticatedScriptsRouteChildren = {
  AuthenticatedScriptsIdRoute: AuthenticatedScriptsIdRoute,
}

const AuthenticatedScriptsRouteWithChildren =
  AuthenticatedScriptsRoute._addFileChildren(AuthenticatedScriptsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedControlRoute: typeof AuthenticatedControlRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHooksRoute: typeof AuthenticatedHooksRoute
  AuthenticatedIdeasRoute: typeof AuthenticatedIdeasRoute
  AuthenticatedInspirationRoute: typeof AuthenticatedInspirationRoute
  AuthenticatedPerformanceRoute: typeof AuthenticatedPerformanceRoute
  AuthenticatedScriptsRoute: typeof AuthenticatedScriptsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedControlRoute: AuthenticatedControlRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHooksRoute: AuthenticatedHooksRoute,
  AuthenticatedIdeasRoute: AuthenticatedIdeasRoute,
  AuthenticatedInspirationRoute: AuthenticatedInspirationRoute,
  AuthenticatedPerformanceRoute: AuthenticatedPerformanceRoute,
  AuthenticatedScriptsRoute: AuthenticatedScriptsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicAutopilotTickRoute: ApiPublicAutopilotTickRoute,
  ApiPublicRenderCallbackRoute: ApiPublicRenderCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
